(use '[clojure.java.shell :only [sh]])
(def lst_i_1 (vector))
(def lst_i_0 (vector))
(def lst_e_1 (vector))
(def lst_e_0 (vector))
(def lst_s_1 (vector))
(def lst_s_0 (vector))
(def lrea_i 0)
(def lrea_e 0)
(def lrea_s 0)
(defn do_task [pal num] (println "Tarea Realizandose de " pal " Tiempo estimado: " num " segundos"))
(defn add_task
[nu nu2 nu3]
(cond
(= nu 0)(if (= nu2 1) (def lst_i_1 (conj lst_i_1 nu3)) (def lst_i_0(conj lst_i_0 nu3)))
(= nu 1) (if (= nu2 1) (def lst_e_1 (conj lst_e_1 nu3)) (def lst_e_0(conj lst_e_0 nu3)))
:else (if (= nu2 1) (def lst_s_1 (conj lst_s_1 nu3)) (def lst_s_0(conj lst_s_0 nu3)))))
(def cont 0)
(def activo true)
(def r_prev_impre false)
(def r_prev_email false)
(def r_prev_es false)
(while (true)
      (do
        (def ocu1 false)
        (def ocu1o false)
        (def ocu2 false)
        (def ocu2o false)
        (def ocu3 false)
        (def ocu3o false)
        (if (= (mod cont 3) 0) (add_task (rand-int 3) (rand-int 2) (+ (rand-int 9) 1)))
        (println "Tareas encoladas de Impresion " (into [] (concat lst_i_1 lst_i_0)))
        (println "Tareas encoladas de Email " (into [] (concat lst_e_1 lst_e_0)))
        (println "Tareas encoladas de E/S " (into [] (concat lst_s_1 lst_s_0)))
        (if (empty? lst_i_1) (if (not (empty? lst_i_0)) (alter-var-root #'ocu1o (constanly true))) (alter-var-root #'ocu1 (constanly true)))
        (if (empty? lst_e_1) (if (not (empty? lst_e_0)) (alter-var-root #'ocu2o (constanly true))) (alter-var-root #'ocu2 (constanly true)))
        (if (empty? lst_s_1) (if (not (empty? lst_s_0)) (alter-var-root #'ocu3o (constanly true))) (alter-var-root #'ocu3 (constanly true)))
        (cond
          (r_prev_impre)
          (do
              (alter-var-root #'ocu1 (constanly false))
              (alter-var-root #'ocu1o (constanly false))
              (if (and (and (and (empty? lst_e_1) (empty? lst_e_0)) (empty? lst_s_1)) (empty? lst_s_0)) (do
                                                                                                            (if (empty? lst_i_1) (alter-var-root #'ocu1 (constanly false)) (alter-var-root #'ocu1 (constanly true)))
                                                                                                            (if (empty? lst_i_0) (alter-var-root #'ocu1o (constanly false)) (alter-var-root #'ocu1o (constanly true)))
                                                                                                          )
                )
            )
          (r_prev_email)
          (do
              (alter-var-root #'ocu2 (constanly false))
              (alter-var-root #'ocu2o (constanly false))
              (do (if (and (empty? lst_s_1) (empty? lst_s_0)) (do (alter-var-root #'ocu2 (constanly false)) (alter-var-root #'ocu2o (constanly false))) (do (alter-var-root #'ocu1 (constanly false)) (alter-var-root #'ocu1o (constanly false))))
                  (if (and (and (and (empty? lst_i_1) (empty? lst_i_0)) (empty? lst_s_1)) (empty? lst_s_0)) (do
                                                                                                            (if (empty? lst_e_1) (alter-var-root #'ocu2 (constanly false)) (alter-var-root #'ocu2 (constanly true)))
                                                                                                            (if (empty? lst_e_0) (alter-var-root #'ocu2o (constanly false)) (alter-var-root #'ocu2o (constanly true)))
                                                                                                          )
                    )
                )
            )
          (r_prev_es)
          (do
            (alter-var-root #'ocu3 (constanly false))
            (alter-var-root #'ocu3o (constanly false))
            (if (and (and (and (empty? lst_e_1) (empty? lst_e_0)) (empty? lst_i_1)) (empty? lst_i_0)) (do
                                                                                                          (if (empty? lst_s_1) (alter-var-root #'ocu3 (constanly false)) (alter-var-root #'ocu3 (constanly true)))
                                                                                                          (if (empty? lst_s_0) (alter-var-root #'ocu3o (constanly false)) (alter-var-root #'ocu3o (constanly true)))
                                                                                                          )
              )
            )
          )
        (if (activo)
          (cond
            (ocu1)(do
                    (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_impre (constanly true))
                    (alter-var-root #'r_prev_es (constanly false))
                    (alter-var-root #'r_prev_email (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_i_1)))
                    (alter-var-root #'lst_i_1 (constanly (into[] (rest lst_i_1))))
                    (alter-var-root #'palabra (constanly "Impresion"))
                    )
            (ocu1o)(do
                     (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_impre (constanly true))
                    (alter-var-root #'r_prev_es (constanly false))
                    (alter-var-root #'r_prev_email (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_i_0)))
                    (alter-var-root #'lst_i_0 (constanly (into[] (rest lst_i_0))))
                    (alter-var-root #'palabra (constanly "Impresion"))
                     )
            (ocu2)(do
                    (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_email (constanly true))
                    (alter-var-root #'r_prev_es (constanly false))
                    (alter-var-root #'r_prev_impre (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_e_1)))
                    (alter-var-root #'lst_e_1 (constanly (into[] (rest lst_e_1))))
                    (alter-var-root #'palabra (constanly "Email"))
                    )
            (ocu2o)(do
                     (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_email (constanly true))
                    (alter-var-root #'r_prev_es (constanly false))
                    (alter-var-root #'r_prev_impre (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_e_0)))
                    (alter-var-root #'lst_e_0 (constanly (into[] (rest lst_e_0))))
                    (alter-var-root #'palabra (constanly "Email"))
                     )
            (ocu3)(do
                    (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_es (constanly true))
                    (alter-var-root #'r_prev_email (constanly false))
                    (alter-var-root #'r_prev_impre (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_s_1)))
                    (alter-var-root #'lst_s_1 (constanly (into[] (rest lst_s_1))))
                    (alter-var-root #'palabra (constanly "E/S"))
                    )
            (ocu3o)(do
                     (alter-var-root #'activo (constanly false))
                    (alter-var-root #'r_prev_es (constanly true))
                    (alter-var-root #'r_prev_email (constanly false))
                    (alter-var-root #'r_prev_impre (constanly false))
                    (alter-var-root #'num_proc (constanly (first lst_s_0)))
                    (alter-var-root #'lst_s_0 (constanly (into[] (rest lst_s_0))))
                    (alter-var-root #'palabra (constanly "E/S"))
                     )
            :else (do
                    (alter-var-root #'num_proc (constanly "Unknown"))
                    (alter-var-root #'palabra(constanly "Waiting")))
            )
          (alter-var-root #'num_proc dec)
          )
        (do_task palabra num_proc)
        (if (= num_proc 0) (do
                             (alter-var-root #'activo (constanly true))
                             (println "Tarea Terminada")
                             (cond
                               (= palabra "Impresion") (alter-var-root #'lrea_i inc)
                               (= palabra "Email") (alter-var-root #'lrea_e inc)
                               (= palabra "E/S") (alter-var-root #'lrea_s inc)
                               )

                             ) )

        (println "Tareas realizadas de Impresion " lrea_i)
        (println "Tareas realizadas de Email " lrea_e)
        (println "Tareas realizadas de E/S " lrea_s)
        (println "Siguiente tarea en " (- 3 (mod cont 3)) " segundos")
        (alter-var-root #'cont inc)
        (Thread/sleep 1000)
        (println (sh "clear"))
         )
  )

